### ISSUE TITLE
Issue with NPM V5.3.0

### ISSUE THREAD

**Issue by harmon25** [nitin42/redocx#2]
Not uncommon for new versions of npm to break babel or something on a few projects.
Installing dependencies in a fresh new npm module using newest npm version results in an error like this:

```
Error: Cannot find module 'react/lib/checkPropTypes'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\harmon\Desktop\redocx-testing\node_modules\react-dom\lib\checkReactTypeSpec.js:13:22)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\harmon\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

This may be a Just a Windows problem..
Removing `node_modules` folder, and reinstalled dependencies using `yarn install` resolved the problem!

Figure I would make a post for people looking to try this out, that run into the same issue.
Very cool library!

**Comment by nitin42** [comment]
Thank you! I will look into this issue further.  Everything works fine with `yarn` right ?

**Comment by harmon25** [comment]
Yes! Is working fine with `yarn`

May want to add an additional step in the README for installing dependencies:
`npm install --save-dev babel-cli babel-core babel-preset-env babel-preset-react babel-preset-stage-0`

Do not think this is really an issue with this package so much as npm... would not worry much about it - just make sure people know of the problem - earlier versions of npm probably work fine.

**Comment by nitin42** [comment]
Thanks @harmon25! Would you mind creating a PR for this (installing dependencies) ?
